package coderunner;

import blockly.dgir.compiler.java.JavaCompiler;
import core.utils.logging.DungeonLogger;
import dgir.vm.api.DapServerUtils;
import dgir.vm.dap.DapServer;
import org.jetbrains.annotations.Nullable;
import server.Server;

import java.io.IOException;
import java.util.Optional;

import static dgir.dialect.builtin.BuiltinOps.ProgramOp;

/**
 * This class is used to run Java code generated by the Blockly language. It compiles the code
 * dynamically.
 *
 * <p>It uses the Java Compiler API to compile the code and then uses reflection to execute it. The
 * code is executed in a separate thread to avoid blocking the main thread. The class also provides
 * methods to check if the code is currently running and to stop the execution of the code.
 *
 * <p>This class is a singleton, meaning that there is only one instance of it in the application.
 *
 * @see Server Server
 */
public class BlocklyCodeRunner {
  private static final DungeonLogger LOGGER = DungeonLogger.getLogger(BlocklyCodeRunner.class);
  private static BlocklyCodeRunner instance;

  private final DapServer dapServer;

  private static final String baseCode =
"""
import Dungeon.Direction;
import Dungeon.Hero;
import Dungeon.IO;
import Dungeon.ItemType;
import Dungeon.LevelElement;
import Dungeon.Arrays;

public class Main {
  %s
}
""";

  // private constructor for singleton
  private BlocklyCodeRunner() {
    dapServer = DapServerUtils.createServer();
    try {
      dapServer.start();
    } catch (IOException e) {
      throw new RuntimeException("Failed to start DAP server", e);
    }
    DebugPauseBridge.install(dapServer);
  }

  /**
   * Returns the instance of the BlocklyCodeRunner.
   *
   * @return The instance of the BlocklyCodeRunner.
   */
  public static BlocklyCodeRunner instance() {
    if (instance == null) {
      instance = new BlocklyCodeRunner();
    }
    return instance;
  }

  /**
   * Returns {@code true} while the VM that was started by the last {@link #compileAndRunCode} call
   * is still executing.
   *
   * @return {@code true} if the VM thread is alive
   */
  public boolean isRunning() {
    return dapServer.isVmRunning();
  }

  /**
   * Requests the current program to stop and interrupts the VM thread so any blocking wait inside
   * an op runner is unblocked immediately.
   *
   * <p>This is a no-op when nothing is running.
   */
  public void stopExecution() {
    dapServer.stopVm();
  }

  public void compileAndRunCode(
      String code,
      boolean isCompleteProgram,
      boolean waitForDebugger,
      @Nullable String sourceFileName) {
    compileAndRunCode(code, 0, isCompleteProgram, waitForDebugger, sourceFileName);
  }

  public void compileAndRunCode(
      String code,
      int sleepAfterEachLine,
      boolean completeProgram,
      boolean waitForDebugger,
      @Nullable String sourceFileName) {
    String completeCode;
    if (!completeProgram) {
      completeCode = String.format(baseCode, code);
    } else {
      completeCode = code;
    }
    LOGGER.info(
        "Compiling and running code: "
            + completeCode
            + "for file: "
            + sourceFileName
            + " with sleep: "
            + sleepAfterEachLine
            + " and waitForDebugger: "
            + waitForDebugger);
    Optional<ProgramOp> program =
        JavaCompiler.compileSource(
            completeCode, sourceFileName != null ? sourceFileName : "Main.java");
    if (program.isEmpty()) {
      LOGGER.error("Failed to compile code");
      return;
    }
    try {
      dapServer.reloadProgram(program.get(), waitForDebugger);
    } catch (InterruptedException e) {
      throw new RuntimeException(e);
    }
  }
}
